name: AutoProgram
main: org.openredstone.autoprogram.AutoProgram
version: 1.0.1
description: >
             Automatically program ROMs according to the contents of a text file.
commands:
  autoprogram:
    description: Program ROMs.
